{
 "title": "PZero Main Display",
 "tags": [
  "prototype-zero",
  "latest",
  "live"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "pyrometer", "label": "Pyrometer #", "query": "0,1" },
   { "name": "target_liner_temp", "query": "90" },
   { "name": "pyrometer_zone", "label": "Pyrometer Zones", "query": "0,1,2,3,4,5,6,7" },
   { "name": "fast_window_period", "query": "20s" },
   { "name": "slow_window_period", "query": "120s" }
  ]
 },
 "panels": [
  { "title": "Pressure Upper", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 } },
  { "title": "Pressure Lower", "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 } },
  {
   "title": "Pyrometers : Mean Liner Temperature",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 }
  },
  { "title": "Pyrometer Sensor Temperature", "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 } },
  {
   "title": "Last Synced Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"prototype-zero\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"id\"] =~ /.*/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Pressure Upper", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 } },
  {
   "title": "Pyrometer_${pyrometer} : Liner Temperature",
   "gridPos": { "h": 14, "w": 7, "x": 8, "y": 4 }
  },
  {
   "title": "Pyrometer_0:  Mean Liner Temperature vs Time",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 4 }
  },
  {
   "title": "Pyrometer_0 : Zonal Temperature",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 4 }
  },
  { "title": "Pressure Lower", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 } },
  {
   "title": "Pyrometer_1 :  Mean Liner Temperature vs Time",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 13 }
  },
  {
   "title": "Pyrometer_1 : Zonal Temperature",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 13 }
  },
  { "gridPos": { "h": 4, "w": 7, "x": 8, "y": 18 } },
  {
   "title": "TC's - Upper",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"prototype-zero\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"liner_heater\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /top_TC[0-9]/)\r\n  |> aggregateWindow(every: ${fast_window_period}, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "TC's - Lower",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"prototype-zero\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"liner_heater\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /bot_TC[0-9]/)\r\n  |> aggregateWindow(every: ${fast_window_period}, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Heater Setpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"prototype-zero\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"liner_heater\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"top_setpoint\" or r[\"_field\"] == \"bot_setpoint\")\r\n  |> aggregateWindow(every: ${slow_window_period}, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Heater Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"prototype-zero\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"liner_heater\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^(top|bot)_PID/)\r\n  |> map(fn: (r) => ({r with _value: r._value*(100.0/255.0)}))\r\n  |> aggregateWindow(every: ${slow_window_period}, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}